/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaskelompok;

/**
 *
 * @author jalisgaf
 */
public class Caesar extends javax.swing.JFrame {

    /**
     * Creates new form Caesar
     */
    public static final String ALPHABET = MenuUtama.ALPHABET;

    public Caesar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCaesarEnkripsi = new javax.swing.JLabel();
        jLabelInputEnkripsi = new javax.swing.JLabel();
        jLabelKunciEnkripsi = new javax.swing.JLabel();
        jLabelOutputEnkripsi = new javax.swing.JLabel();
        inputEnkripsi = new javax.swing.JTextField();
        kunciEnkripsi = new javax.swing.JTextField();
        outputEnkripsi = new javax.swing.JTextField();
        tblEnkripsi = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCaesarDekripsi = new javax.swing.JLabel();
        jLabelInputDekripsi = new javax.swing.JLabel();
        jLabelKunciDekripsi = new javax.swing.JLabel();
        jLabelOutputDekripsi = new javax.swing.JLabel();
        inputDekripsi = new javax.swing.JTextField();
        kunciDekripsi = new javax.swing.JTextField();
        outputDekripsi = new javax.swing.JTextField();
        tblDekripsi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caesar");
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));

        jLabelCaesarEnkripsi.setText("Enkripsi Teknik Subsitusi Caesar");

        jLabelInputEnkripsi.setText("Plain Teks");

        jLabelKunciEnkripsi.setText("Pergeseran Kunci");

        jLabelOutputEnkripsi.setText("Chiper Teks");

        inputEnkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEnkripsiActionPerformed(evt);
            }
        });

        kunciEnkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kunciEnkripsiActionPerformed(evt);
            }
        });

        outputEnkripsi.setEditable(false);
        outputEnkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputEnkripsiActionPerformed(evt);
            }
        });

        tblEnkripsi.setText("Proses");
        tblEnkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblEnkripsiActionPerformed(evt);
            }
        });

        jLabelCaesarDekripsi.setText("Dekripsi Teknik Subsitusi Caesar");

        jLabelInputDekripsi.setText("Chiper Teks");

        jLabelKunciDekripsi.setText("Pergeseran Kunci");

        jLabelOutputDekripsi.setText("Plain Teks");

        outputDekripsi.setEditable(false);

        tblDekripsi.setText("Proses");
        tblDekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDekripsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabelCaesarEnkripsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelOutputEnkripsi)
                                .addGap(56, 56, 56)
                                .addComponent(outputEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelKunciEnkripsi)
                                    .addComponent(jLabelInputEnkripsi))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kunciEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(tblEnkripsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabelCaesarDekripsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOutputDekripsi)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInputDekripsi)
                                    .addComponent(jLabelKunciDekripsi))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kunciDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(outputDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(tblDekripsi)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelCaesarEnkripsi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInputEnkripsi)
                    .addComponent(inputEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKunciEnkripsi)
                    .addComponent(kunciEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(tblEnkripsi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutputEnkripsi)
                    .addComponent(outputEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCaesarDekripsi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInputDekripsi)
                    .addComponent(inputDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelKunciDekripsi)
                    .addComponent(kunciDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tblDekripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutputDekripsi)
                    .addComponent(outputDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEnkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblEnkripsiActionPerformed
        // TODO add your handling code here:
        String inputTeks = inputEnkripsi.getText().toLowerCase();
        int inputKunci = Integer.parseInt(kunciEnkripsi.getText());
        String hasil = "";
        for (int i = 0; i < inputTeks.length(); i++) {
            int pos = ALPHABET.indexOf(inputTeks.charAt(i));
            int posHasil = (inputKunci + pos) % 26;
            char charHasil = ALPHABET.charAt(posHasil);
            hasil += charHasil;
        }
        outputEnkripsi.setText(hasil);
    }//GEN-LAST:event_tblEnkripsiActionPerformed

    private void kunciEnkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kunciEnkripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kunciEnkripsiActionPerformed

    private void inputEnkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEnkripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEnkripsiActionPerformed

    private void outputEnkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputEnkripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputEnkripsiActionPerformed

    private void tblDekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDekripsiActionPerformed
        // TODO add your handling code here:
        String inputTeks = inputDekripsi.getText().toLowerCase();
        int inputKunci = Integer.parseInt(kunciDekripsi.getText());
        String hasil = "";
        for (int i = 0; i < inputTeks.length(); i++) {
            int pos = ALPHABET.indexOf(inputTeks.charAt(i));
            int posHasil = (pos - inputKunci) % 26;
            if (posHasil < 0) {
                posHasil += ALPHABET.length();
            }
            char charHasil = ALPHABET.charAt(posHasil);
            hasil += charHasil;
        }
        outputDekripsi.setText(hasil);
    }//GEN-LAST:event_tblDekripsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caesar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputDekripsi;
    private javax.swing.JTextField inputEnkripsi;
    private javax.swing.JLabel jLabelCaesarDekripsi;
    private javax.swing.JLabel jLabelCaesarEnkripsi;
    private javax.swing.JLabel jLabelInputDekripsi;
    private javax.swing.JLabel jLabelInputEnkripsi;
    private javax.swing.JLabel jLabelKunciDekripsi;
    private javax.swing.JLabel jLabelKunciEnkripsi;
    private javax.swing.JLabel jLabelOutputDekripsi;
    private javax.swing.JLabel jLabelOutputEnkripsi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kunciDekripsi;
    private javax.swing.JTextField kunciEnkripsi;
    private javax.swing.JTextField outputDekripsi;
    private javax.swing.JTextField outputEnkripsi;
    private javax.swing.JButton tblDekripsi;
    private javax.swing.JButton tblEnkripsi;
    // End of variables declaration//GEN-END:variables
}
