/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaskelompok;

/**
 *
 * @author jalisgaf
 */
public class Caesar extends javax.swing.JFrame {

    /**
     * Creates new form Caesar
     */
    public static final String ALPHABET = "abcdefghijklmnopqrstuvwxyz";
    
    public Caesar() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCaesarEnkripsi = new javax.swing.JLabel();
        jLabelInputEnkrip = new javax.swing.JLabel();
        jLabelKunciEnkrip = new javax.swing.JLabel();
        jLabelOutputEnkrip = new javax.swing.JLabel();
        tblEnkrip = new javax.swing.JButton();
        kunciEnkrip = new javax.swing.JTextField();
        inputEnkrip = new javax.swing.JTextField();
        outputEnkrip = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCaesarDekripsi = new javax.swing.JLabel();
        jLabelInputDekrip = new javax.swing.JLabel();
        jLabelKunciDekrip = new javax.swing.JLabel();
        jLabelOutputDekrip = new javax.swing.JLabel();
        tblDekrip = new javax.swing.JButton();
        inputDekrip = new javax.swing.JTextField();
        kunciDekrip = new javax.swing.JTextField();
        outputDekrip = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCaesarEnkripsi.setText("Enkripsi Teknik Subsitusi Caesar");

        jLabelInputEnkrip.setText("Plain Teks");

        jLabelKunciEnkrip.setText("Pergeseran Kunci");

        jLabelOutputEnkrip.setText("Chiper Teks");

        tblEnkrip.setText("Proses");
        tblEnkrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblEnkripActionPerformed(evt);
            }
        });

        kunciEnkrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kunciEnkripActionPerformed(evt);
            }
        });

        inputEnkrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEnkripActionPerformed(evt);
            }
        });

        outputEnkrip.setEditable(false);
        outputEnkrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputEnkripActionPerformed(evt);
            }
        });

        jLabelCaesarDekripsi.setText("Deskripsi Teknik Subsitusi Caesar");

        jLabelInputDekrip.setText("Chiper Teks");

        jLabelKunciDekrip.setText("Pergeseran Kunci");

        jLabelOutputDekrip.setText("Plain Teks");

        tblDekrip.setText("Proses");
        tblDekrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDekripActionPerformed(evt);
            }
        });

        outputDekrip.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabelCaesarEnkripsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelOutputEnkrip)
                                .addGap(56, 56, 56)
                                .addComponent(outputEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelKunciEnkrip)
                                    .addComponent(jLabelInputEnkrip))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kunciEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(tblEnkrip))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabelCaesarDekripsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOutputDekrip)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInputDekrip)
                                    .addComponent(jLabelKunciDekrip))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kunciDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(outputDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(tblDekrip)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelCaesarEnkripsi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInputEnkrip)
                    .addComponent(inputEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKunciEnkrip)
                    .addComponent(kunciEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(tblEnkrip)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutputEnkrip)
                    .addComponent(outputEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCaesarDekripsi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInputDekrip)
                    .addComponent(inputDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelKunciDekrip)
                    .addComponent(kunciDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tblDekrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutputDekrip)
                    .addComponent(outputDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEnkripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblEnkripActionPerformed
        // TODO add your handling code here:
        String inputEnkripVar = this.inputEnkrip.getText().toLowerCase();
        int kunciEnkripVar = Integer.parseInt(this.kunciEnkrip.getText());
        
        String enkripStr = "";
        
        for (int i = 0; i < inputEnkripVar.length(); i++)   
        {   
            // get position of each character of inputEnkripVar in ALPHABET   
            int pos = ALPHABET.indexOf(inputEnkripVar.charAt(i));   
              
            // get encrypted char for each char of inputEnkripVar   
            int enkripPos = (kunciEnkripVar + pos) % 26;   
            char enkripChar = ALPHABET.charAt(enkripPos);   
              
            // add encrypted char to encrypted string   
            enkripStr += enkripChar;   
        }   
        
        outputEnkrip.setText(enkripStr);
    }//GEN-LAST:event_tblEnkripActionPerformed

    private void kunciEnkripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kunciEnkripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kunciEnkripActionPerformed

    private void inputEnkripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEnkripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEnkripActionPerformed

    private void outputEnkripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputEnkripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputEnkripActionPerformed

    private void tblDekripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDekripActionPerformed
        // TODO add your handling code here:
        String inputDekripVar = this.inputDekrip.getText().toLowerCase();
        int kunciDekripVar = Integer.parseInt(this.kunciDekrip.getText());
        
        String dekripStr = "";
        
        for (int i = 0; i < inputDekripVar.length(); i++)   
        {   
              
            // get position of each character of inputStr in ALPHABET   
            int pos = ALPHABET.indexOf(inputDekripVar.charAt(i));   
              
            // get decrypted char for each char of inputStr   
            int dekripPos = (pos - kunciDekripVar) % 26;   
              
            // if decryptPos is negative   
            if (dekripPos < 0){   
                dekripPos = ALPHABET.length() + dekripPos;   
            }   
            char dekripChar = ALPHABET.charAt(dekripPos);   
              
            // add decrypted char to decrypted string   
            dekripStr += dekripChar;   
        }      
        
        outputDekrip.setText(dekripStr);
    }//GEN-LAST:event_tblDekripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caesar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputDekrip;
    private javax.swing.JTextField inputEnkrip;
    private javax.swing.JLabel jLabelCaesarDekripsi;
    private javax.swing.JLabel jLabelCaesarEnkripsi;
    private javax.swing.JLabel jLabelInputDekrip;
    private javax.swing.JLabel jLabelInputEnkrip;
    private javax.swing.JLabel jLabelKunciDekrip;
    private javax.swing.JLabel jLabelKunciEnkrip;
    private javax.swing.JLabel jLabelOutputDekrip;
    private javax.swing.JLabel jLabelOutputEnkrip;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kunciDekrip;
    private javax.swing.JTextField kunciEnkrip;
    private javax.swing.JTextField outputDekrip;
    private javax.swing.JTextField outputEnkrip;
    private javax.swing.JButton tblDekrip;
    private javax.swing.JButton tblEnkrip;
    // End of variables declaration//GEN-END:variables
}
