/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaskelompok;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author fahmi
 */
public class PolyalphabeticalDinamis extends javax.swing.JFrame {

    /**
     * Creates new form PilihKunci
     */
    public PolyalphabeticalDinamis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFramePolyalphabeticalDinamis = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tblDekripsi = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        tblEnkripsi = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelKunciEnkripsi = new javax.swing.JPanel();
        tblProses = new javax.swing.JButton();
        jumlahKunci = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jFramePolyalphabeticalDinamis.setSize(new java.awt.Dimension(400, 500));

        jLabel5.setText("Enkripsi Teknik Polyalphabetical Dinamis");

        jTextField3.setEditable(false);

        jLabel6.setText("Plain Teks");

        jLabel4.setText("Chiper Teks");

        jTextField6.setEditable(false);

        jLabel8.setText("Dekripsi Teknik Polyalphabetical Dinamis");

        jLabel9.setText("Plain Teks");

        jLabel11.setText("Chiper Teks");

        tblDekripsi.setText("Proses");
        tblDekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDekripsiActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tblEnkripsi.setText("Proses");
        tblEnkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblEnkripsiActionPerformed(evt);
            }
        });

        jPanelKunciEnkripsi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelKunciEnkripsiLayout = new javax.swing.GroupLayout(jPanelKunciEnkripsi);
        jPanelKunciEnkripsi.setLayout(jPanelKunciEnkripsiLayout);
        jPanelKunciEnkripsiLayout.setHorizontalGroup(
            jPanelKunciEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelKunciEnkripsiLayout.setVerticalGroup(
            jPanelKunciEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFramePolyalphabeticalDinamisLayout = new javax.swing.GroupLayout(jFramePolyalphabeticalDinamis.getContentPane());
        jFramePolyalphabeticalDinamis.getContentPane().setLayout(jFramePolyalphabeticalDinamisLayout);
        jFramePolyalphabeticalDinamisLayout.setHorizontalGroup(
            jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                        .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(tblEnkripsi)))
                                            .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(75, 75, 75)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelKunciEnkripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel8))
                            .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(76, 76, 76)
                                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(tblDekripsi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFramePolyalphabeticalDinamisLayout.setVerticalGroup(
            jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePolyalphabeticalDinamisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jPanelKunciEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblEnkripsi)
                .addGap(18, 18, 18)
                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(tblDekripsi)
                .addGap(18, 18, 18)
                .addGroup(jFramePolyalphabeticalDinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProses.setText("Proses");
        tblProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblProsesActionPerformed(evt);
            }
        });

        jumlahKunci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel1.setText("Enkripsi Teknik Polyalphabetical Dinamis");

        jLabel2.setText("Pilih Jumlah Kunci");

        jLabel3.setText("*Jumlah 1 Sampai 10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(jumlahKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tblProses))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jumlahKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(tblProses)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblProsesActionPerformed
        // TODO add your handling code here:

        SwingUtilities.invokeLater(() -> {
            jPanelKunciEnkripsi.setLayout(new BoxLayout(jPanelKunciEnkripsi, BoxLayout.Y_AXIS));
            Integer jlhKunci = (Integer) jumlahKunci.getSelectedIndex() + 1;

            JPanel[] panelInputEnkripsi = new JPanel[jlhKunci];

            for (int i = 0; i < panelInputEnkripsi.length; i++) {
                panelInputEnkripsi[i] = new JPanel();
                JLabel labelKunciEnkripsi = new JLabel("Kunci " + (i + 1) + " :");
                JTextField inputKunciEnkripsi = new JTextField(20);
                panelInputEnkripsi[i].add(labelKunciEnkripsi);
                panelInputEnkripsi[i].add(inputKunciEnkripsi);
                jPanelKunciEnkripsi.add(panelInputEnkripsi[i]);

                jFramePolyalphabeticalDinamis.add(jPanelKunciEnkripsi);
            }

            jFramePolyalphabeticalDinamis.pack();
            jFramePolyalphabeticalDinamis.setVisible(true);
        });
    }//GEN-LAST:event_tblProsesActionPerformed

    private void tblDekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDekripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDekripsiActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tblEnkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblEnkripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEnkripsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyalphabeticalDinamis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyalphabeticalDinamis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyalphabeticalDinamis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyalphabeticalDinamis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolyalphabeticalDinamis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFramePolyalphabeticalDinamis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelKunciEnkripsi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> jumlahKunci;
    private javax.swing.JButton tblDekripsi;
    private javax.swing.JButton tblEnkripsi;
    private javax.swing.JButton tblProses;
    // End of variables declaration//GEN-END:variables
}
